version: '3.3'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4000:5173"
    volumes:
      - .: /app
      - /app/node_modules
    depends_on:
      - api

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - PORT=3000
    volumes:
      - ./api:/app
      - /app/node_modules

networks:
  default:
    driver: bridge 